Djangoooo4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from poll.forms import LoginForm
from accounts.views import (login_view, logout_view, register_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('poll.urls')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('codescript.urls'), name="save_scripts"),

]
# allow apps to upload files to the server
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codescript/urls.py
from django.conf.urls import url

from codescript import views

urlpatterns = [
    url(r'^$', views.code_scripts, name="codeScripts"),

    url(r'^save$', views.save_code_script, name="save_scripts"),
    url(r'^codenow/$', views.new_code_script, name="codenow"),
    url(r'^codenow/(?P<id>\d+)/$', views.load_code_script, name='codescript'),

]

poll/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^fake/$', views.home, name="home"),
    url(r'^list/$', views.list, name="list"),
    url(r'^about/$', views.about_us, name="about"),
    url(r'^useraccount/$', views.user_account, name="useraccount"),
    url(r'^article/$', views.articles_list, name="articles"),
    url(r'^tellme/', include("tellme.urls")),
    url(r'^article/(?P<id>\d)/$',views.article_details,name="details"),
    url(r'^article/(?P<category>\w+)/$',views.article_category),


]

codescript/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class CodeScript(models.Model):
    creator = models.ForeignKey('auth.User')
    title = models.CharField(max_length=25)
    # banner = models.FileField(upload_to='codescript/%y/%m/%d')
    html_file_path = models.TextField(max_length=255)
    css_file_path = models.TextField(max_length=255)
    js_file_path = models.TextField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    pub_date = models.DateTimeField(default=timezone.now)
    stars = models.IntegerField(default=0)

    def upload(self):
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("codescript", kwargs={"id": self.id})

    class Meta:
        ordering = ["-created_at"]

codescript/forms.py
from django import forms

from codescript.models import CodeScript


class CodeForm(forms.ModelForm):
    class Meta:
        model = CodeScript
        fields = ["title","creator"]
        widgets = {
            "title": forms.TextInput(),
            "creator": forms.HiddenInput()
        }

codescript/views.py
import os

import simplejson
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from Djangoooo4.settings import BASE_DIR
from codescript.forms import CodeForm
from codescript.models import CodeScript


def code_scripts(request):
    list = CodeScript.objects.all()
    paginator = Paginator(list, 3)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        list = paginator.page(paginator.num_pages)
    return render(request, "codeScripts.html", {"list": list})


@login_required
def save_code_script(request):
    context = {'error': ''}
    homeDir = os.getcwd()

    if request.method == 'POST':
        # form must contain 'content' field
        if request.POST.__contains__('title'):
            codeFolder = "codes"
            user_id = request.user.id
            path = os.path.join(BASE_DIR, 'media', codeFolder, str(user_id), request.POST['title'])
            if not os.path.exists(path):
                os.makedirs(path)
            os.chdir(path)
            writeFile(request.POST['html'], "temp.html", context)
            writeFile(request.POST['js'], "temp.js", context)
            writeFile(request.POST['css'], "temp.css", context)
            html_path = os.path.join(path, "temp.html")
            css_path = os.path.join(path, "temp.css")
            js_path = os.path.join(path, "temp.js")
            code = CodeScript(title=request.POST['title'],
                              html_file_path=html_path,
                              css_file_path=css_path,
                              js_file_path=js_path,
                              creator=request.user)
            code.save()
            print(code.id)
            return_dict = {'message': 'code script saved ', 'code': ''}
            json = simplejson.dumps(return_dict)
            os.chdir(homeDir)
            return HttpResponse(json)
        else:
            context['error'] += 'Request doen not contain any content to create the file.\n'
    else:
        context['error'] += 'Request type must be POST.\n'

    return_dict = {'message': 'code script saved ', 'code': ''}
    # json = simplejson.dumps(return_dict)
    return HttpResponseRedirect("codenow/", "success")


@login_required
def load_code_script(request, id):
    context = {'error': ''}
    code_script = CodeScript.objects.get(id=id)
    html = code_script.html_file_path
    css = code_script.css_file_path
    js = code_script.js_file_path
    codeName = code_script.title
    readFile(html, context)
    htmlContent = context['fileContent']
    readFile(css, context)
    cssContent = context['fileContent']
    readFile(js, context)
    jsContent = context['fileContent']
    form = CodeForm(request.POST or None,initial={'title':codeName})

    context = {'code': code_script, 'form': form, 'html': htmlContent, 'css': cssContent, 'js': jsContent,
               'title': codeName}
    return render(request, "CodeNow.html", context)


@login_required
def new_code_script(request):
    form = CodeForm(request.POST or None)
    context = {'form': form}
    return render(request, "CodeNow.html", context)


# file handling function

def openFile(fileName, mode, context):
    # open file using python's open method
    # by default file gets opened in read mode
    try:
        fileHandler = open(fileName, mode)
        return {'opened': True, 'handler': fileHandler}
    except IOError:
        context['error'] += 'Unable to open file ' + fileName + '\n'
    except:
        context['error'] += 'Unexpected exception in openFile method.\n'
    return {'opened': False, 'handler': None}


def readFile(fileName, context):
    # open file in read-only mode
    fileHandler = openFile(fileName, 'r', context)

    if fileHandler['opened']:
        # create Django File object using python's file object
        file = File(fileHandler['handler'])

        # we have atleast empty file now
        context['fileContent'] = ''
        # use chunks to iterate over the file in chunks.
        # this is helpful when file is large enough.
        # '10' represents the size of each chunk
        for chunk in file.chunks(10):
            context['fileContent'] += chunk

        # make sure to close the file before exit
        file.close()


def writeFile(content, fileName, context):
    # open file write mode
    fileHandler = openFile(fileName, 'w', context)

    if fileHandler['opened']:
        # create Django File object using python's file object
        file = File(fileHandler['handler'])
        # write content into the file
        file.write(content)
        # flush content so that file will be modified.
        file.flush()
        # close file
        file.close()


def deleteFile(fileName, context):
    try:
        os.remove(fileName)
    except:
        context['error'] += 'Exception raised while deleting temp file.\n'
    pass

templates/CodeNow.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block styleblock %}
    <style type="text/css" media="screen">
        body {
            background-color: #2b9b7c;
            background-size: cover;
            padding: 0;
            margin: 0;
        }

        .code {
            position: relative;
        }

        #editorhtml {
            margin-right: 0;
            width: 100%;
            height: 300px;
            padding: 0;

        }

        #editorcss {
            width: 100%;
            height: 300px;
            padding: 1em;
        }

        #editorjs {
            width: 100%;
            height: 300px;
            padding: 1em;
        }

        .coderow .col-md-4 {
            margin: 0;
            padding: 0;
        }

        .preview {
            position: relative;
            top: -15px;
            border: #2aabd2 2px solid;
            box-sizing: border-box;
            padding: 0;
            box-shadow: inset 2px 2px 0px #000;
            background: #fff;
            height: 500px;
            overflow: auto;
        }
    </style>
{% endblock %}
{% block contentblock %}


    <form method='POST' class="form btn" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' class=" btn btn-default" value='save'/>

    </form>

    <div class="container-fluid">
        <div class="row coderow">
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <h5 style="text-align:center;color: black"><b>HTML</b></h5>
                    <div class="code">
                        <div id="editorhtml">{% if html %}{{ html }}{% endif %}</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <h5 style="text-align:center;color: black"><b>CSS</b></h5>
                    <div class="code">
                        <div id="editorcss">{% if css %}{{ css }}{% endif %}</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="code">
                        <h5 style="text-align:center;color: black"><b>JAVASCRIPT</b></h5>
                        <div id="editorjs">{% if js %}{{ js }}{% endif %}</div>
                    </div>
                </div>
            </div>
        </div>
        <span id="css_area">
        </span>
        <div class="coderow row preview">
        </div>
        <span id="js_area">
            <script>

            </script>
        </span>
    </div>

{% endblock %}

{% block javascript %}
    <!-- load ace -->
    <script src="{% static 'vendors/ace/src/ace.js' %}"></script>
    <!-- load ace language tools -->
    <script src="{% static 'vendors/ace/src/ext-language_tools.js' %}"></script>
    <script>
        $(document).ready(function () {
            // trigger extension
            ace.require("ace/ext/language_tools");
            var editor = ace.edit("editorhtml");
            editor.session.setMode("ace/mode/html");
            editor.setTheme("ace/theme/monokai");
            editor.session.getLength();

            document.getElementById('editorhtml').style.fontSize = '18px';
            document.getElementById('editorcss').style.fontSize = '18px';
            document.getElementById('editorjs').style.fontSize = '18px';

            // enable autocompletion and snippets
            editor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });

            // trigger extension
            ace.require("ace/ext/language_tools");
            var editorcss = ace.edit("editorcss");
            editorcss.session.setMode("ace/mode/css");
            editorcss.setTheme("ace/theme/monokai");

            // enable autocompletion and snippets
            editorcss.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });
            //load data from html
            var preview = $('div.preview');
            var css_area = $('span#css_area');
            var js_area = $('span#js_area');
            var codescript = "";


            // trigger extension
            ace.require("ace/ext/language_tools");
            var editorjs = ace.edit("editorjs");
            editorjs.session.setMode("ace/mode/javascript");
            editorjs.setTheme("ace/theme/monokai");

            editorjs.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });

            editorcss.getSession().on('change', function (e) {
                var cssCode = "<style>" + editorcss.getValue() + "</style>";
                css_area.html(cssCode);
            });
            editor.getSession().on('change', function (e) {
                var htmlCode = editor.getValue();
                preview.html(htmlCode)
            });
            editorjs.getSession().on('change', function (e) {
                var jsCode = editorjs.getValue();
                js_area.html(jsCode);
            });
            window.onload = function (e) {
                var cssCode = "<style>" + editorcss.getValue() + "</style>";
                var jsCode = editorjs.getValue();
                var htmlCode = editor.getValue();
                css_area.html(cssCode);
                preview.html(htmlCode)
                js_area.html(jsCode);

            };

            //window.location.replace("save");
            $(".form").submit(function (e) {
                var html = editor.getValue();
                var js = editorjs.getValue();
                var css = editorcss.getValue();
                var title = $('#id_title').val();
                // similar behavior as an HTTP redirect
                $.ajax({
                    type: 'post',
                    url: "/save",
                    data: {
                        'html': html,
                        'js': js,
                        'css': css,
                        'title': title
                    },
                    success: function (data) {
                        alert("success")
                    }
                });

                e.preventDefault();
                return false;
            });


            function clear_everything() {
                editor.setValue("");
                editorcss.setValue("");
                editorjs.setValue("");
            }

        });
    </script>

{% endblock %}

templates/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block contentblock %}
    <style>
        section {
            width: 100%;
            float: left;
        }

        .image-block {
            float: left;
            width: 100%;
            margin-bottom: 100px;
            margin-left: 10%;
        }

        .banner-section {
            background-image: url("{% static 'images/programming-593312_1920.jpg' %}");
            height: 70%;
            width: 100%;
            left: 0;
            position: absolute;
            top: 0;
            background-position: 0;
        }
    </style>
    <section class="banner-section">
    </section>
    <section class="post-content-section">
    <div class="container">

    <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 post-title-block" style="color: white">

        <h1 class="text-center" style="padding-top: 10%">We are Team CO-IDE</h1>
        <ul class="list-inline text-center">
            <li>CODE |</li>
            <li>LEARN |</li>
            <li>SHARE|</li>
        </ul>
    </div>

    <section class="row content_about page-content">

        <div class="container">
            <div class="row">

                <div class="col-sm-8 who_we_are" style="padding-top: 15%">
                    <h6 class="label label-defatult about_var">who we are</h6>
                    <h3 class="team_page_title">About Us</h3>
                    <p class="team_page_para about_var">Co-ide team provide coding playground for programmers and
                        non-programmers:</p>

                    <p>IDE is plateform which provide coding features for developing the Software, CO-IDE is smart Web
                        IDE, it is smart because it performs on real
                        time preview feature.It is specially for those who work as web developer but it is open source
                        that is free to all either they are professional
                        programmers or beginners in programming.CO-IDE supports the basic languages such as html,css and
                        javascript which are must to be learn as a web
                        developer,because these languages are common in every programming language either python or
                        php.Spending time over here provide you knowledge
                        gaining and keep you sharp in Coding ,We update articles on each languages which is beneficial
                        for beginners who have less knowledge about HTML,
                        CSS and JAVASCRIPT.Through the articles they can gain the basic knowledge about tags,functions
                        and styling functions supported by all these
                        languages.</p>
                    <p><u>Functioning based on the realtime preview which supports for CSS,HTMl and JAVASCRIPT.</u>
                        When you login into CO-IDE, just switch over coding ground to start coding, and save your script
                        into our database, you can embed your code into
                        another website, you need to copy whole code written in html or css or javascript and paste
                        there, make your styling of webpage according
                        to your own written script.
                        If there is any problem using CO-IDE just give your feedback to us ,Our team solve that problem
                        anyhow and also you can give your comments over
                        articles or scipts, through facebook plugin or our comment system.
                        <br><h4><b>Thank You</b></h4><br>
                    <h5><b>Team Co-IDE,</b></h5></p>
                </div>
            </div>
        </div>
        <div class="container">

            <div class="row">
                <div class="col-sm-8">
                    <h4 class="team_page_title">Developer Team</h4>
                    <p class="team_page_para about_var"><u>Trio of team developed a codingground to accomplish easy
                        programming
                        and
                        learning.</u></p>
                    <div class="w3-container w3-center w3-animate-zoom">
                        <div class="row">
                            <div class="col-xs-3 col-sm-4 col-md-3 team_member">
                                <img src="{% static 'images/dev.jpg' %}" alt="" class="img-responsive">
                                <h4>Devansh Mishra</h4>
                                <h6>Co-Founder <br>and President</h6>
                            </div>
                            <div class="col-xs-3 col-sm-4 col-md-3 team_member">
                                <img src="{% static 'images/ajeet.jpg' %}" alt="" class="img-responsive">
                                <h4>Ajeet Singh Vashisth</h4>
                                <h6>Co-Founder &amp; <br>President</h6>
                            </div>
                            <div class="col-xs-3 col-sm-4 col-md-3 team_member">
                                <img src="{% static 'images/ajay.jpg' %}" alt="" class="img-responsive">
                                <h4>Ajay sonker</h4>
                                <h6>Co-Founder &amp; <br>President</h6>
                            </div>
                        </div>
                    </div>

                    <div class="pull-right emergency-contact">
                        <div class="pull-left">
                            <span><i class="fa fa-envelope-o"></i></span>
                            <div class="infos_col">
                                <h6>email us at</h6>
                                <h5>devanshmishra872@gmail.com</h5>
                                <a href="mailto:ajaysonker14@gmail.com"><h5>ajaysonker14@gmail.com</h5></a>
                                <a href="mailto:ajiet.vashishth.8@gmail.com"><h5> ajiet.vashishth.8@gmail.com</h5></a>
                            </div>
                        </div>
                    </div>


                    <div class="pull-left">
                        <span class="rotate"><i class="fa fa-phone"></i></span>
                        <div class="infos_col">
                            <h6>call us now</h6>
                            <h4>+918765945870</h4>
                            <h4>+918299180054</h4>
                            <h4>+917071237096</h4>
                        </div>
                    </div>
                </div>
            </div>

    </section>


{% endblock %}

templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block contentblock %}
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=747197475458366";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <section class="row page-header">
        <div class="container">
            <marquee><h3><b>“That's the thing about people who think they hate computers. What they really hate is lousy
                programmers.”</b></h3></marquee>
        </div>
    </section>

    <section class="row blog-content page-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <article class="post post-type-gallery-row">
                        <div class="row featured-contents">
                            <div class="post-gallery">
                                <div class="item"><img src="{% static "images/glasses-272399_1920.jpg" %}" alt=""></div>
                                <div class="item"><img src="{% static "images/htmlarticle.png" %}" alt=""></div>
                                <div class="item"><img src="{% static "images/cssartcile.png" %}" alt=""></div>
                                <div class="item"><img src="{% static "images/javascript.jpg" %}" alt=""></div>
                                <div class="item"><img src="{% static "images/bookarticle.jpg" %}" alt=""></div>
                            </div>
                        </div>
                    </article>
                    <h1>{{ article.category }}  </h1>
                    {% for article in list %}
                        <article class="post post-type-gallery row">
                            <div class="row article-body">

                                <img src="{{ article.banner.url }}" class="img-responsive" alt="">
                                <h3 class="post-title"><a href="article.html">{{ article.title }}</a></h3>
                                <ul class="post-meta nav">
                                    <li class="post-date"><i class="fa fa-calendar-o"></i> <a
                                            href="#">{{ article.created_at }}</a>
                                    </li>
                                    <li class="post-comments"><i class="fa fa-comments"></i> <a
                                            href="#">{{ article.comments }} comment</a>
                                    </li>
                                    <li class="posted-by"><i class="fa fa-user"></i>posted by: <a
                                            href="#">{{ article.author }}</a></li>
                                    <li class="category"><i class="fa fa-folder"></i>category: <a
                                            href="#">{{ article.category }}</a></li>
                                </ul>
                                <div class="post-excerpt row">
                                    <p class="content">{{ article.content|slice:":100" }}</p>

                                    <a href="{{ request.path }}{{ article.id }}"
                                       class="btn-primary btn-outline dark">Read
                                        more
                                    </a>

                                </div>

                            </div>
                        </article>
                    {% endfor %}
                    <ul class="pagination">
                        {% if list.has_previous %}
                            <li><a href="?page={{ list.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in  list.paginator.page_range %}
                            {% if  list.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if  list.has_next %}
                            <li><a href="?page={{ list.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                    <div class="fb-comments" data-href="http://127.0.0.1:8000/article/" data-numposts="5"></div>
                </div>
                <div class="col-md-4 sidebar post-sidebar">
                    <div class="row m0 widget widget-search">
                        <h4 class="widget-title">search</h4>
                        <form action="#" class="row m0 search-form" method="get" role="search">
                            <script>
                                (function () {
                                    var cx = '013837355815072367840:mjnag-qhowo';
                                    var gcse = document.createElement('script');
                                    gcse.type = 'text/javascript';
                                    gcse.async = true;
                                    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
                                    var s = document.getElementsByTagName('script')[0];
                                    s.parentNode.insertBefore(gcse, s);
                                })();
                            </script>
                            <gcse:search></gcse:search>
                        </form>
                    </div>

                    <div class="row m0 widget widget-recent-posts">
                        <h4 class="widget-title">Recent Added Articles</h4>
                        <div class="media recent-post">
                            <ul type="list-style-type:square">
                                {% for article in list %}
                                    <div class="media-left">
                                    <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
                                {% endfor %}</div>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/article_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block contentblock %}
    <article class="post post-type-gallery row">
        <div class="row article-body">

            <div style="background-image: url('{{ article.banner.url }}');margin-left:10%;height: 360px;width:650px;margin-top: 3% "></div>
            <div class="col-md-10 col-md-offset-1">
                <h2 class="post-title"><a href="article.html">{{ article.title }}</a></h2>
                <ul class="post-meta nav">
                    <li class="post-date"><i class="fa fa-calendar-o"></i> <a
                            href="#">{{ article.timestamp }}</a>
                    </li>

                    <li class="posted-by"><i class="fa fa-user"></i>posted by: <a
                            href="#">{{ article.author }}</a></li>
                    <li class="category"><i class="fa fa-folder"></i>category: <a
                            href="#">{{ article.category }}</a></li>
                    <li class="post-comments"><i class="fa fa-comments">{{ article.comments }}</i> <a href="#"></a>
                    </li>
                </ul>
                <div class="post-excerpt row">
                    <p class="content">{{ article.content|linebreaksbr|addslashes }}</p>
                </div>

            </div>
        </div>

        <div class="col-md-8 col-md-offset-1">

            <p class='lead'>Comments</p>
            {% if request.user.is_authenticated %}
                <form method="POST" action="{{ request.path }}"> {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type='hidden' value='{{ article.id }}' name="article_id">
                    <input type='submit' value='Post comment' class='btn btn-default'>
                </form>
            {% else %}
                <p>You must login to comment </p>
            {% endif %}
            <hr/>
            {% for comment in comments %}


                <p>{{ comment.content }}</p>
                <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago |
                    {% if comment.children.count > 0 %}{{ comment.children.count }} Comment
                        {% if comment.children.count > 1 %}s{% endif %} | {% endif %}   </footer>
                <div class='comment-reply'>
                    {% for child_comment in comment.children %}
                        <blockquote>
                            <p>{{ child_comment.content }}</p>
                            <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }}
                                ago
                            </footer>

                        </blockquote>
                    {% endfor %}
                </div>
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.AbsolutePath }}">
                    Share on Facebook|
                </a>
                <a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}">
                  Share on Twitter
                </a>
                <hr/>
            {% endfor %}
        </div>

    </article>


{% endblock %}